In [2]:
import numpy as np

In [268]:
def next_table_group(current_table_group: int):
    #current_table= 0 or 1
    r = np.random.binomial(1,0.25)               #proba 0.25 to stay in the table => r = 0 => same table group
    return (1-r)*current_table_group + r*(1-current_table_group) #  r=0 ? current_table_group : 1-current_table_group

def next_table(current_table_group: int, K : int, k : int):
    return current_table_group*K + k

def coin_value(current_table : int, coin_tab_prob: np.ndarray):
    return np.random.binomial(n=1,p=coin_tab_prob[current_table],size=2)

def dice_value(coin_values: np.ndarray, player: int, dice_proba_tab: int):
    res=np.zeros(2,int)
    for i,coin in enumerate(coin_values):
        res[i] = 1+np.random.choice(6,p=dice_proba_tab[player][coin])
    return np.sum(res)

def sum_values(dice_results: np.ndarray):
    return np.sum(dice_results)

def experiment_player(player: int, tab_dice : np.ndarray,tab_coin: np.ndarray):
    r=1
    K= int(len(tab_coin)/2)
    res = np.zeros(K)
    for k in range(K):
        r=next_table_group(r)
        table=next_table(r,K,k)
        c = coin_value(table,tab_coin)
        res[k] = dice_value(c,player,tab_dice)
    return res

def experiment(tab_dice : np.ndarray,tab_coin: np.ndarray):
    K= int(len(tab_coin)/2)
    N = len(tab_dice)
    res = np.zeros((N,K),int)
    for n in range(N):
        res[n] = experiment_player(n,tab_dice,tab_coin)
    return res

In [253]:
bias_dice = 1
player = 5
tab_dice = generator_dice_proba_bias6_biasN(player+1,bias_dice)
tab_coin = generator_coin_proba_uniform(K)
s= experiment(tab_dice,tab_coin)
s

array([[ 5.,  7.,  7., 10.,  3.,  6.,  9.],
       [10.,  3.,  7.,  8.,  4.,  7.,  3.],
       [ 7.,  4., 12., 11.,  5.,  4.,  5.],
       [ 8.,  3., 11., 10.,  3.,  9.,  8.],
       [10., 10., 12.,  2.,  9.,  7., 12.],
       [ 9.,  8., 12., 12., 10.,  7.,  8.]])

In [34]:
def generator_coin_proba_uniform(K : int):
    return 0.5*np.ones(2*K)

def generator_coin_biais(K : int, pa: float):
    return pa*np.ones(2*K)

def generator_coin_biais_group0(K : int, pa: float):
    return np.concatenate([pa*np.ones(K),0.5*np.ones(K)])

def generator_dice_proba_uniform(N : int):
    return 1/6*np.ones((N,2,6))

def generator_dice_proba_uniform_bias6(N : int, k : int):
    a = 1/6*np.ones((N,1,6))
    b = np.array([[[1/(6+k),1/(6+k),1/(6+k),1/(6+k),1/(6+k),(1+k)/(6+k)]]]*N)
    return np.concatenate([a,b],axis=1)

def generator_dice_proba_bias6_biasN(N : int, k : int):
    b=[]
    a = np.array([[[1/(6+k),1/(6+k),1/(6+k),1/(6+k),1/(6+k),(1+k)/(6+k)]]]*N)
    for i in range(N):
        b.append([[1/(6+i),1/(6+i),1/(6+i),1/(6+i),1/(6+i),(1+i)/(6+i)]])
    b = np.array(b)
    return np.concatenate([a,b],axis=1)

In [63]:
generator_coin_biais_group0(3,0.2)

array([0.5, 0.5, 0.5, 0.2, 0.2, 0.2])

In [20]:
generator_dice_proba_uniform(2)

array([[[0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667],
        [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667]],

       [[0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667],
        [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667]]])

In [53]:
generator_dice_proba_uniform_bias6(2,4)

array([[[0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667],
        [0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
         0.5       ]],

       [[0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667],
        [0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
         0.5       ]]])

In [60]:
generator_dice_proba_bias6_biasN(2,4)

array([[[0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
         0.5       ],
        [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
         0.16666667]],

       [[0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
         0.5       ],
        [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
         0.28571429]]])

In [67]:
tab_dice[player]

array([[0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429],
       [0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
        0.54545455]])

In [36]:
b = np.array([[1/7,1/7,1/7,1/7,1/7,2/7]]*6)
b[3][2]=5
b

array([[0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429],
       [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429],
       [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429],
       [0.14285714, 0.14285714, 5.        , 0.14285714, 0.14285714,
        0.28571429],
       [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429],
       [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.28571429]])

In [68]:
np.empty((5,2,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 7.56596412e-307]],

       [[4.45066125e-308, 1.69121096e-306],
        [7.56587585e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307]],

       [[1.02359984e-306, 1.69118108e-306],
        [1.69111725e-306, 1.69118923e-306]],

       [[1.11260144e-306, 6.89812281e-307],
        [2.22522596e-306, 1.50008880e+248]]])

In [197]:
def p_one_dice_r(k: int, K: int, ri: int, player: int, tab_coin: np.ndarray, tab_dice: np.ndarray):
    res = np.zeros(6)
    pA = tab_coin[ri*K+k]
    #ri*K+k=K+k or k
    for i in range(6):
        res[i] = pA*tab_dice[player][0][i]+(1-pA)*tab_dice[player][1][i]
    return res

def p_s_r(k: int, K: int, s: int, ri: int, player: int, tab_coin: np.ndarray, tab_dice: np.ndarray):
    p=p_one_dice_r(k,K,ri,player,tab_coin,tab_dice)
    res=0
    sum_val = s[k]
    for i in range(max(0,sum_val-7),min(6,sum_val-1)):
        res+=p[i]*p[sum_val-i-2]
    return res

def p_r_r(ri: int, ri_previous: int):
    if (ri==ri_previous):
        return 0.25
    else:
        return 0.75
    
def alpha(ri : int, ri_previous : int, i: int, K: int, 
          tab_alpha: np.ndarray, player: int, tab_dice: np.ndarray,
          tab_coin: np.ndarray, s : np.ndarray):
          #tab_alpha[i][ri][ri_previous]=alpha_i(ri,ri_previous)
    if(type(tab_alpha)==type(None)): # initiate if needed
        tab_alpha = np.empty((K,2,2))
        tab_alpha[:]=np.nan
    # print(type(ri_previous))
    if(np.isnan(tab_alpha[i][ri][ri_previous])):
        p_s = p_s_r(i, K, s, ri, player, tab_coin,tab_dice)
        p_r = p_r_r(ri,ri_previous)
        if(i==(K-1)):
            bonus = 1/(np.power(0.25,int(K/2))*1/6*1/6) 
            #to avoid to small value. Since we compute a ratio of alpha at the end, it is ok
            tab_alpha[i][ri][ri_previous] = p_s*p_r*bonus
        else:
            tab_alpha, r_next_0 = alpha(0,ri,i+1,K,tab_alpha,player,tab_dice,tab_coin,s)
            tab_alpha, r_next_1 = alpha(1,ri,i+1,K,tab_alpha,player,tab_dice,tab_coin,s)
            tab_alpha[i][ri][ri_previous] = p_s*p_r*(r_next_0+r_next_1)
    if(np.isnan(tab_alpha[i][ri][ri_previous])):
        print(i,ri,ri_previous)
    return tab_alpha,tab_alpha[i][ri][ri_previous]

def p_ri(ri: int, ri_previous: int, i: int, s: np.ndarray, K: int, 
          tab_alpha: np.ndarray, player: int, tab_dice: np.ndarray,
          tab_coin: np.ndarray):
    tab_alpha,r = alpha(ri,ri_previous,i, K, tab_alpha, player,tab_dice,tab_coin,s)
    tab_alpha,r_minus = alpha(1-ri,ri_previous,i, K, tab_alpha, player,tab_dice,tab_coin,s)
    return tab_alpha,r/(r+r_minus)

# def p_r1(r1: int, i: int, s: np.ndarray, K: int, 
#           tab_alpha: np.ndarray, player: int, tab_dice: np.ndarray,
#           tab_coin: np.ndarray):
#     tab_alpha,r = alpha(r1,1,i, K, tab_alpha, player,tab_dice,tab_coin,s)
#     tab_alpha,r_minus = alpha(1-r1,1,i, K, tab_alpha, player,tab_dice,tab_coin,s)
#     return tab_alpha,r/(r+r_minus)

def p_all_r(r: np.ndarray, s: np.ndarray, player: int, tab_dice : np.ndarray, tab_coin: np.ndarray,  tab_alpha: np.ndarray=None):
    K = int(len(tab_coin)/2)
    if(type(tab_alpha)==type(None)): # initiate if needed
        tab_alpha = np.empty((K,2,2))
        tab_alpha[:]=np.nan
    # suppose r0=1
    tab_alpha,res = p_ri(r[0],1,0,s,K,tab_alpha,player,tab_dice,tab_coin)
    for i in range(1,K):
        tab_alpha,temp = p_ri(r[i],r[i-1],i,s,K,tab_alpha,player,tab_dice,tab_coin)
        #update tab_alpha all the time in order to compute it only once
        res=temp*res
    return res,tab_alpha

In [162]:
type(1-1)

int

In [198]:
c= generator_coin_proba_uniform(3)
d= generator_dice_proba_uniform(2)
res=0
tab_alpha=None
for i in range(2):
    for j in range(2):
        for k in range(2):
            a,tab_alpha =p_all_r(np.array([i,j,k]),np.array([3,5,8]),1,d,c,tab_alpha)
            res+=a
res

0.9999999999999999

In [298]:
import plotly.graph_objects as go
import numpy as np
from itertools import product

def generate_R_i(r_previous: int, i: int, K: int, tab_alpha:np.ndarray, s: np.ndarray, player: int, tab_dice : np.ndarray, tab_coin: np.ndarray):
    tab_alpha, a_1 = alpha(1,r_previous,i,K,tab_alpha,player,tab_dice,tab_coin,s)
    tab_alpha, a_0 = alpha(0,r_previous,i,K,tab_alpha,player,tab_dice,tab_coin,s)
    p = a_1/(a_1+a_0)
    res = np.random.binomial(1,p)
    return tab_alpha,res

def generate_random_value(s: np.ndarray, player: int, tab_dice : np.ndarray, tab_coin: np.ndarray, tab_alpha: np.ndarray=None):
    K = int(len(tab_coin)/2)
    r=np.empty(K,int)
    if(type(tab_alpha)==type(None)): # initiate if needed
        tab_alpha = np.empty((K,2,2))
        tab_alpha[:]=np.nan
    # suppose r0=1
    tab_alpha,a = generate_R_i(1,0,K,tab_alpha,s,player,tab_dice,tab_coin)
    r[0] = int(a)
    for i in range(1,K):
        tab_alpha,a = generate_R_i(r[i-1],i,K,tab_alpha,s,player,tab_dice,tab_coin)
        #update tab_alpha all the time in order to compute it only once
        r[i] = int(a)
    return r,tab_alpha

def decode(trans: np.ndarray):
    res=0
    pow =1
    for i,a in enumerate(trans):
        res= res + a*pow
        pow=pow*2
    return res

def Verify_Model(attempt:int, s: np.ndarray, player: int, tab_dice : np.ndarray, tab_coin: np.ndarray, tab_alpha: np.ndarray=None, printage:bool=False):
    K=int(len(tab_coin)/2)
    possible = [np.array(i) for i in product(range(2), repeat=K)]
    proba = np.empty(len(possible))
    count = np.zeros(len(possible))
    for i in range(attempt):
        a,tab_alpha = generate_random_value(s,player,tab_dice,tab_coin,tab_alpha)
        count[decode(a)]+=1
    for poss in possible:
        a, tab_alpha=p_all_r(poss,s,player,tab_dice,tab_coin,tab_alpha)
        proba[decode(poss)] = a
    print("Gap on "+str(attempt)+" attempts:\t",np.sum(np.abs(proba-count/attempt)))
    if (printage):
        fig = go.Figure(data=[go.Scatter(x=[decode(poss) for poss in possible],y=proba, customdata=possible, hovertemplate='Tables=%{customdata}<br>Probability=%{y}<extra></extra>', mode="markers", name="Real probability"),
                        go.Scatter(x=[decode(poss) for poss in possible],y=count/attempt, customdata=possible, hovertemplate='Tables=%{customdata}<br>Probability=%{y}<extra></extra>', mode="markers", name="Observed reality on "+str(attempt)+" tests")])
        fig.show()

In [304]:
K=5
bias_dice = 1
player = 5
attempt = 3000
tab_dice = generator_dice_proba_bias6_biasN(player+1,bias_dice)
tab_dice_2 = generator_dice_proba_uniform_bias6(player+1,bias_dice)
tab_coin = generator_coin_biais_group0(K,0.1)
s_n= experiment(tab_dice,tab_coin)
s_2= np.random.randint(2,13,K)
s_3= np.ones(K,int)*12
Verify_Model(attempt,s_n[player],player,tab_dice,tab_coin,None,True)
Verify_Model(attempt,s_2,player,tab_dice,tab_coin,None,True)
Verify_Model(attempt,s_3,player,tab_dice,tab_coin,None,True)
Verify_Model(attempt,s_3,player,tab_dice_2,tab_coin,None,True)

Gap on 3000 attempts:	 0.06994748380262142


Gap on 3000 attempts:	 0.061020205423038876


Gap on 3000 attempts:	 0.0694451017799377


Gap on 3000 attempts:	 0.07513707701814706
